//package javaapplication174;
//
//import java.awt.Color;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import java.text.DateFormat;
//import java.text.SimpleDateFormat;
//import java.util.Date;
//import javax.swing.JColorChooser;
//import javax.swing.JDialog;
//import javax.swing.JFormattedTextField;
//import javax.swing.JOptionPane;
//import javax.swing.JSlider;
//import javax.swing.SwingWorker;
//
//public class SetFrame extends javax.swing.JFrame {
//    
//    SwingWorker swingWorker;
//    boolean start;
//    Object appTime;
//    long razlika;
//    
//    public SetFrame() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        jCheckBox1 = new javax.swing.JCheckBox();
//        jCheckBox2 = new javax.swing.JCheckBox();
//        jButton1 = new javax.swing.JButton();
//        jComboBox1 = new javax.swing.JComboBox<>();
//        startButton = new javax.swing.JButton();
//        stopButton = new javax.swing.JButton();
//        jTextField1 = new javax.swing.JTextField();
//        jTextField2 = new javax.swing.JTextField();
//        jLabel1 = new javax.swing.JLabel();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jCheckBox1.setText("On time");
//        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
//            public void itemStateChanged(java.awt.event.ItemEvent evt) {
//                jCheckBox1ItemStateChanged(evt);
//            }
//        });
//        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jCheckBox1ActionPerformed(evt);
//            }
//        });
//
//        jCheckBox2.setText("Countdown (mins)");
//        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
//            public void itemStateChanged(java.awt.event.ItemEvent evt) {
//                jCheckBox2ItemStateChanged(evt);
//            }
//        });
//
//        jButton1.setText("Choose color");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
//
//        startButton.setText("Start");
//        startButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                startButtonButtonActionPerformed(evt);
//            }
//        });
//
//        stopButton.setText("Stop");
//        stopButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                stopButtonActionPerformed(evt);
//            }
//        });
//
//        jLabel1.setText("No color selected");
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
//                        .addGap(31, 31, 31)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jCheckBox2)
//                                .addGap(9, 9, 9))
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(73, 73, 73))
//                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                            .addGroup(layout.createSequentialGroup()
//                                .addGap(80, 80, 80)
//                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
//                        .addGap(12, 12, 12))
//                    .addGroup(layout.createSequentialGroup()
//                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(startButton)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(stopButton)))
//                .addGap(66, 66, 66))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap(41, Short.MAX_VALUE)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addGap(24, 24, 24)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jCheckBox2)
//                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(49, 49, 49)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jButton1)
//                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(33, 33, 33)
//                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(startButton)
//                    .addComponent(stopButton))
//                .addContainerGap(23, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>                        
//
//    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
//        jCheckBox2.setEnabled(false);
//        jTextField2.setEnabled(false);
//    }                                           
//
//    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
////        jCheckBox1ActionPerformed(evt);
//    }                                          
//
//    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
//        jCheckBox1.setEnabled(false);
//        jTextField1.setEnabled(false);
//    }                                           
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        JColorChooser jcc = new JColorChooser();
//        JDialog dialog = JColorChooser.createDialog(jcc, "Choose color", true, jcc, new ActionListener() {  
//        @Override  
//        public void actionPerformed(ActionEvent ae) {  
//          Color c = jcc.getColor();  
//          jLabel1.setText("Color selected");  
//          jLabel1.setOpaque(true);  
//          jLabel1.setBackground(c);  
//        }  
//      },null);  
//      dialog.setVisible(true);
//    }                                        
//
//    private void startButtonButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
//        jCheckBox1.setEnabled(false);
//        jCheckBox2.setEnabled(false);
//        jTextField1.setEnabled(false);
//        jTextField2.setEnabled(false);
//        jButton1.setEnabled(false);
//        jLabel1.setEnabled(false);
//        jComboBox1.setEnabled(false);
//        startButton.setEnabled(false);
//        
////        Data d = new Data();
////        d.setColor(jLabel1.getBackground());
//////        d.setSpeed(s.getValue());
////
////        if(jCheckBox1.isSelected()) {
////            start = true;
////            Object set = jTextField1
////            String setTime = new SimpleDateFormat("HH:mm:ss").format(set);  
////            String appTime1 = new SimpleDateFormat("HH:mm:ss").format(appTime);
////            try {  
////            SimpleDateFormat form = new SimpleDateFormat("HH:mm:ss");  
////            Date d1 = form.parse(setTime);  
////            Date d2 = form.parse(appTime1);  
////            razlika = d1.getTime() - d2.getTime();
////            } catch (Exception e) {  
////            JOptionPane.showMessageDialog(null, e.getMessage());
////            }
////        }
//        
////        swingWorker = new SwingWorker() {
////            @Override
////            protected Object doInBackground() throws Exception {
////                ColorFrame.startTheShow();
////                return null;
////            }
////        };
//        DateFormat df = new SimpleDateFormat();
//        JFormattedTextField txxdate = new JFormattedTextField(df);
//        Data d = new Data();  
//        
//      d.setColor(jLabel1.getBackground());  
//      d.setSpeed(jComboBox1.getValue());  
//        
//      if (jCheckBox1.isSelected()){  
//        start = true;  
//        Object set = jTextField1.getValue();  
//        String setTime = new SimpleDateFormat("HH:mm:ss").format(set);  
//        String appTime1 = new SimpleDateFormat("HH:mm:ss").format(appTime);  
//        try {  
//          SimpleDateFormat form = new SimpleDateFormat("HH:mm:ss");  
//          Date d1 = form.parse(setTime);  
//          Date d2 = form.parse(appTime1);  
//          razlika = d1.getTime() - d2.getTime();  
//        } catch (Exception e) {  
//          JOptionPane.showMessageDialog(null, e.getMessage());  
//        }           
//          
//        swingWorker = new SwingWorker() {  
//          @Override  
//          protected Object doInBackground() throws Exception {  
//            Thread.sleep(razlika);  
//            ColorFrame.startTheShow();  
//            while(start){  
//              ColorFrame.cf.getContentPane().setBackground(d.getColor());  
//              Thread.sleep(d.getSpeed());  
//              ColorFrame.cf.getContentPane().setBackground(new Color (44,62,80));  
//              Thread.sleep(d.getSpeed());  
//            }     
//            return null;   
//          }  
//          @Override  
//          protected void done () {  
//            JOptionPane.showMessageDialog(null,"Thanks for watching!");  
//            ColorFrame.cf.dispose();  
//            d.setColor(null);
//            jTextField1.setValue(new java.util.Date());  
//            start = false;  
//          }  
//        };  
//        swingWorker.execute();  
//      }  
//        
//      else if (jCheckBox2.isSelected()) {  
//        d.setTime2((Integer)jTextField2.getValue());  
//        start = true;  
//        swingWorker = new SwingWorker() {         
//          @Override  
//          protected Object doInBackground() throws Exception {  
//            Thread.sleep(d.getTime2()*60000);  
//            ColorFrame.startTheShow();  
//            while(start){  
//              ColorFrame.cf.getContentPane().setBackground(d.getColor());  
//              Thread.sleep(d.getSpeed());  
//              ColorFrame.cf.getContentPane().setBackground(new Color (44,62,80));  
//              Thread.sleep(d.getSpeed());  
//            }   
//            return null;  
//          }  
//          @Override  
//          protected void done () {  
//            JOptionPane.showMessageDialog(null,"Thanks for watching!");  
//            ColorFrame.cf.dispose();  
//            d.setColor(null);  
//            start = false;  
//          }  
//        };  
//        swingWorker.execute();  
//      }  
//      else {  
//        JOptionPane.showMessageDialog(this, "No checkbox selected!");  
//      }
//        
//    }                                                 
//
//    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        swingWorker.cancel(false);
//        jCheckBox1.setEnabled(true);
//        jCheckBox2.setEnabled(true);
//        jTextField1.setEnabled(true);
//        jTextField2.setEnabled(true);
//        jButton1.setEnabled(true);
//        jLabel1.setEnabled(true);
//        jComboBox1.setEnabled(true);
//        startButton.setEnabled(true);
//        jLabel1.setBackground(null);
//        jLabel1.setText("No color selected");
//    }                                          
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SetFrame().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify                     
//    private javax.swing.JButton jButton1;
//    private javax.swing.JCheckBox jCheckBox1;
//    private javax.swing.JCheckBox jCheckBox2;
//    private javax.swing.JComboBox<String> jComboBox1;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JTextField jTextField1;
//    private javax.swing.JTextField jTextField2;
//    private javax.swing.JButton startButton;
//    private javax.swing.JButton stopButton;
//    // End of variables declaration                   
//}
